In [9]:
import pandas as pd

In [10]:
# info = {
#     "Name" : ["Rahul", "Ajoy", "Somu"],
#     "CGPA" : [9.5, 8.3, 8.5]
# }
# df = pd.DataFrame(info)
# print(df)

In [11]:
# df

In [12]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
3

In [13]:
s = pd.Series([23, 24, 25, 26, 27, "abc"], index = ["Adam", "Eve", "Bob", "Alice", "Charlie", 25])
print(s)
print(s["Bob"])
print(s.index)

Adam        23
Eve         24
Bob         25
Alice       26
Charlie     27
25         abc
dtype: object
25
Index(['Adam', 'Eve', 'Bob', 'Alice', 'Charlie', 25], dtype='object')

In [14]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)

s1[0] = 100
changed = s1.drop(0)
print(s1)
print(changed)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
#Csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [17]:
#json data
df = pd.read_json("employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [18]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [39]:
#Methods
df.head() # starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [40]:
df.tail(2) #last 5 rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [41]:
df.sample(5) #random rows

   ID    Name  Age Department  Salary
8   9     Ian   35         IT   75000
1   2     Bob   32         IT   72000
3   4   David   45  Marketing   91000
9  10   Julia   30    Finance   60000
7   8  Hannah   26  Marketing   47000

In [42]:
df.info() #Description

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

In [43]:
df.shape #r X c

(10, 5)

In [44]:
df.describe() #statistical summary

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [45]:
df.columns #Header names

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [46]:
df.nunique() #Unique value for each column

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64